"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { formatMoney } from "@/app/lib/commerce";
import type { AnnouncementRecord, CatalogProduct, ContactMessageRecord, OrderRecord, ReviewRecord } from "@/db";

const statuses = ["pending", "confirmed", "production", "shipped", "delivered", "cancelled"];
const statusNames: Record<string, string> = { pending: "Bekliyor", confirmed: "Onaylandı", production: "Üretimde", shipped: "Kargoda", delivered: "Teslim edildi", cancelled: "İptal" };
type Tab = "products" | "orders" | "reviews" | "announcements" | "contacts";

export function AdminConsole({ products, orders, reviews, announcements, contacts }: { products: CatalogProduct[]; orders: OrderRecord[]; reviews: ReviewRecord[]; announcements: AnnouncementRecord[]; contacts: ContactMessageRecord[] }) {
  const router = useRouter();
  const [message, setMessage] = useState("");
  const [tab, setTab] = useState<Tab>("products");
  const request = async (url: string, init: RequestInit) => { const response = await fetch(url, init); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "İşlem tamamlanamadı."); setMessage("Kaydedildi. Liste yenileniyor…"); window.setTimeout(() => { router.refresh(); setMessage("Kaydedildi."); }, 500); };
  const run = async (action: () => Promise<void>, fallback: string) => { try { setMessage("Kaydediliyor…"); await action(); } catch (error) { setMessage(error instanceof Error ? error.message : fallback); } };

  const createProduct = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); return run(() => request("/api/admin/products", { method: "POST", body: new FormData(event.currentTarget) }), "Ürün kaydedilemedi."); };
  const updateProduct = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request(`/api/admin/products/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ price: Math.round(Number(form.get("price")) * 100), salePrice: form.get("salePrice") ? Math.round(Number(form.get("salePrice")) * 100) : null, stock: Number(form.get("stock")), availability: form.get("availability"), active: form.get("active") === "on", featured: form.get("featured") === "on" }) }), "Ürün güncellenemedi."); };
  const uploadImage = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); return run(() => request(`/api/admin/products/${id}/image`, { method: "POST", body: new FormData(event.currentTarget) }), "Görsel yüklenemedi."); };
  const updateOrder = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: form.get("status"), note: form.get("note") }) }), "Sipariş güncellenemedi."); };
  const updateReview = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request(`/api/admin/reviews/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: form.get("status"), adminReply: form.get("adminReply") }) }), "Yorum güncellenemedi."); };
  const createAnnouncement = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request("/api/admin/announcements", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), slug: form.get("slug"), summary: form.get("summary"), body: form.get("body"), imageUrl: form.get("imageUrl"), published: form.get("published") === "on", featured: form.get("featured") === "on" }) }), "Duyuru kaydedilemedi."); };
  const updateAnnouncement = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request(`/api/admin/announcements/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: form.get("title"), summary: form.get("summary"), body: form.get("body"), imageUrl: form.get("imageUrl"), published: form.get("published") === "on", featured: form.get("featured") === "on" }) }), "Duyuru güncellenemedi."); };
  const deleteAnnouncement = (id: string) => { if (!window.confirm("Bu duyuru kalıcı olarak silinsin mi?")) return; return run(() => request(`/api/admin/announcements/${id}`, { method: "DELETE" }), "Duyuru silinemedi."); };
  const updateContact = (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(() => request(`/api/admin/contacts/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: form.get("status") }) }), "Mesaj güncellenemedi."); };

  const pendingReviewCount = reviews.filter((review) => review.status === "pending").length;
  const tabs: Array<{ id: Tab; label: string; count: number }> = [{ id: "products", label: "Ürünler", count: products.length }, { id: "orders", label: "Siparişler", count: orders.length }, { id: "reviews", label: "Yorumlar", count: pendingReviewCount }, { id: "announcements", label: "Duyurular", count: announcements.length }, { id: "contacts", label: "Mesajlar", count: contacts.filter((item) => item.status === "new").length }];
  return <div className="admin-shell"><aside><b>MAREL / YÖNETİM</b>{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}<span>{item.count}</span></button>)}<Link href="/">Mağazaya dön ↗</Link></aside><main>{message ? <div className="admin-message">{message}</div> : null}
    {tab === "products" && <><header><span>KATALOG YÖNETİMİ</span><h1>Ürünler ve fiyatlar</h1><p>Fiyat, stok, Google ürün kategorisi ve ürün görsellerini yönetin.</p></header><details className="admin-create" open><summary>+ Yeni ürün ekle</summary><form onSubmit={createProduct} className="admin-form-grid"><label>Ürün adı<input name="name" required /></label><label>SKU<input name="sku" required /></label><label>Kategori<input name="category" required /></label><label>URL adı<input name="slug" /></label><label>Fiyat (₺)<input name="price" type="number" min="0" step="0.01" required /></label><label>İndirimli fiyat<input name="salePrice" type="number" min="0" step="0.01" /></label><label>Stok<input name="stock" type="number" min="0" required /></label><label>Google kategorisi<input name="googleProductCategory" defaultValue="Home & Garden > Decor > Window Treatments" /></label><label className="span-2">Açıklama<textarea name="description" rows={3} /></label><label>Ürün görseli<input name="image" type="file" accept="image/png,image/jpeg,image/webp" /></label><label className="check"><input name="featured" type="checkbox" /> Öne çıkar</label><button type="submit">Ürünü kaydet</button></form></details><section className="admin-product-list">{products.map((product) => <article key={product.id}><div className="admin-product-image"><Image unoptimized src={product.image} alt={product.name} fill sizes="90px" /></div><div className="admin-product-name"><small>{product.sku} · {product.category}</small><h2>{product.name}</h2><a href={`/urunler/${product.slug}`} target="_blank">Ürünü görüntüle ↗</a></div><form onSubmit={(event) => updateProduct(event, product.id)} className="admin-inline-form"><label>Fiyat<input name="price" type="number" step="0.01" defaultValue={(product.price / 100).toFixed(2)} /></label><label>İndirim<input name="salePrice" type="number" step="0.01" defaultValue={product.salePrice ? (product.salePrice / 100).toFixed(2) : ""} /></label><label>Stok<input name="stock" type="number" defaultValue={product.stock} /></label><label>Durum<select name="availability" defaultValue={product.availability}><option value="in_stock">Stokta</option><option value="out_of_stock">Tükendi</option><option value="preorder">Ön sipariş</option><option value="backorder">Tedarik</option></select></label><label className="check"><input name="active" type="checkbox" defaultChecked={Boolean(product.active)} /> Yayında</label><label className="check"><input name="featured" type="checkbox" defaultChecked={Boolean(product.featured)} /> Öne çıkan</label><button type="submit">Güncelle</button></form><form onSubmit={(event) => uploadImage(event, product.id)} className="admin-image-form"><input name="image" type="file" accept="image/png,image/jpeg,image/webp" required /><button type="submit">Yeni görsel yükle</button></form></article>)}</section></>}
    {tab === "orders" && <><header><span>SİPARİŞ OPERASYONU</span><h1>Siparişler</h1><p>Onay, üretim, kargo ve teslimat durumlarını güncelleyin.</p></header><section className="admin-order-list">{orders.length ? orders.map((order) => <article key={order.id}><div><small>{new Date(order.createdAt).toLocaleString("tr-TR")}</small><h2>{order.orderNumber}</h2><p>{order.customerName} · {order.email} · {order.phone}</p><strong>{formatMoney(order.total, order.currency)}</strong></div><span className={`order-status status-${order.status}`}>{statusNames[order.status] ?? order.status}</span><form onSubmit={(event) => updateOrder(event, order.id)}><select name="status" defaultValue={order.status}>{statuses.map((status) => <option key={status} value={status}>{statusNames[status]}</option>)}</select><input name="note" placeholder="Müşteri veya operasyon notu" /><button type="submit">Durumu kaydet</button></form></article>) : <div className="empty-state">Henüz sipariş yok.</div>}</section></>}
    {tab === "reviews" && <><header><span>TOPLULUK YÖNETİMİ</span><h1>Müşteri yorumları</h1><p>Yorumları inceleyin, yayınlayın ve Marel adına yanıtlayın. <strong>{pendingReviewCount} yorum onay bekliyor.</strong></p></header><section className="admin-review-list">{reviews.length ? reviews.map((review) => <article className={review.status === "pending" ? "is-pending" : ""} key={review.id}><div className="admin-review-copy"><div className="admin-review-top"><span>{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</span><strong>{review.status === "pending" ? "Onay bekliyor" : review.status === "approved" ? "Yayında" : "Reddedildi"}</strong></div><h2>{review.title}</h2><small>{review.authorName} · {review.productName ?? "Genel deneyim"} · {new Date(review.createdAt).toLocaleDateString("tr-TR")}</small><p>{review.body}</p></div><form onSubmit={(event) => updateReview(event, review.id)}><select name="status" defaultValue={review.status}><option value="pending">Onay bekliyor</option><option value="approved">Yayınla</option><option value="rejected">Reddet</option></select><textarea name="adminReply" defaultValue={review.adminReply} rows={3} placeholder="Marel yanıtı" /><button type="submit">Yorumu kaydet</button></form></article>) : <div className="empty-state">Henüz müşteri yorumu yok.</div>}</section></>}
    {tab === "announcements" && <><header><span>İÇERİK YÖNETİMİ</span><h1>Duyurular</h1><p>Rehberleri ve kampanya duyurularını oluşturun, yayınlayın veya arşivleyin.</p></header><details className="admin-create" open><summary>+ Yeni duyuru oluştur</summary><form onSubmit={createAnnouncement} className="admin-content-form"><label>Başlık<input name="title" required /></label><label>URL adı<input name="slug" placeholder="otomatik oluşturulur" /></label><label className="span-2">Özet<textarea name="summary" rows={2} required /></label><label className="span-2">Duyuru metni<textarea name="body" rows={6} required /></label><label className="span-2">Görsel yolu<input name="imageUrl" defaultValue="/images/hero/marel-honeycomb-hero-v3.png" /></label><label className="check"><input name="published" type="checkbox" /> Yayınla</label><label className="check"><input name="featured" type="checkbox" /> Öne çıkar</label><button type="submit">Duyuruyu kaydet</button></form></details><section className="admin-announcement-list">{announcements.map((item) => <article key={item.id}><div className="admin-announcement-image"><Image unoptimized src={item.imageUrl} alt="" fill sizes="180px" /></div><form onSubmit={(event) => updateAnnouncement(event, item.id)}><label>Başlık<input name="title" defaultValue={item.title} /></label><label>Özet<textarea name="summary" rows={2} defaultValue={item.summary} /></label><label>Metin<textarea name="body" rows={5} defaultValue={item.body} /></label><label>Görsel yolu<input name="imageUrl" defaultValue={item.imageUrl} /></label><div><label className="check"><input name="published" type="checkbox" defaultChecked={Boolean(item.published)} /> Yayında</label><label className="check"><input name="featured" type="checkbox" defaultChecked={Boolean(item.featured)} /> Öne çıkan</label><button type="submit">Güncelle</button><button className="admin-delete" type="button" onClick={() => deleteAnnouncement(item.id)}>Sil</button></div></form></article>)}</section></>}
    {tab === "contacts" && <><header><span>MÜŞTERİ İLETİŞİMİ</span><h1>Gelen mesajlar</h1><p>İletişim formundan gelen talepleri okuyun ve sonuçlandırın.</p></header><section className="admin-contact-list">{contacts.length ? contacts.map((item) => <article key={item.id} className={item.status === "new" ? "is-new" : ""}><div><span>{item.subject}</span><h2>{item.name}</h2><small>{item.email} · {item.phone || "Telefon yok"} · {new Date(item.createdAt).toLocaleString("tr-TR")}</small><p>{item.message}</p></div><form onSubmit={(event) => updateContact(event, item.id)}><select name="status" defaultValue={item.status}><option value="new">Yeni</option><option value="read">Okundu</option><option value="resolved">Sonuçlandı</option></select><button type="submit">Durumu kaydet</button></form></article>) : <div className="empty-state">Henüz mesaj yok.</div>}</section></>}
  </main></div>;
}
