"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { formatMoney } from "@/app/lib/commerce";
import type { CatalogProduct, OrderRecord } from "@/db";

const statuses = ["pending", "confirmed", "production", "shipped", "delivered", "cancelled"];
const statusNames: Record<string, string> = { pending: "Bekliyor", confirmed: "Onaylandı", production: "Üretimde", shipped: "Kargoda", delivered: "Teslim edildi", cancelled: "İptal" };

export function AdminConsole({ products, orders }: { products: CatalogProduct[]; orders: OrderRecord[] }) {
  const [message, setMessage] = useState("");
  const [tab, setTab] = useState<"products" | "orders">("products");
  const request = async (url: string, init: RequestInit) => { const response = await fetch(url, init); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "İşlem tamamlanamadı."); setMessage("Kaydedildi. Sayfa yenileniyor…"); window.setTimeout(() => window.location.reload(), 500); };

  const createProduct = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage("Kaydediliyor…"); try { await request("/api/admin/products", { method: "POST", body: new FormData(event.currentTarget) }); } catch (error) { setMessage(error instanceof Error ? error.message : "Ürün kaydedilemedi."); } };
  const updateProduct = async (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request(`/api/admin/products/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ price: Math.round(Number(form.get("price")) * 100), salePrice: form.get("salePrice") ? Math.round(Number(form.get("salePrice")) * 100) : null, stock: Number(form.get("stock")), availability: form.get("availability"), active: form.get("active") === "on", featured: form.get("featured") === "on" }) }); } catch (error) { setMessage(error instanceof Error ? error.message : "Ürün güncellenemedi."); } };
  const uploadImage = async (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); try { await request(`/api/admin/products/${id}/image`, { method: "POST", body: new FormData(event.currentTarget) }); } catch (error) { setMessage(error instanceof Error ? error.message : "Görsel yüklenemedi."); } };
  const updateOrder = async (event: React.FormEvent<HTMLFormElement>, id: string) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: form.get("status"), note: form.get("note") }) }); } catch (error) { setMessage(error instanceof Error ? error.message : "Sipariş güncellenemedi."); } };

  return <div className="admin-shell">
    <aside><b>MAREL / YÖNETİM</b><button className={tab === "products" ? "active" : ""} onClick={() => setTab("products")}>Ürünler <span>{products.length}</span></button><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}>Siparişler <span>{orders.length}</span></button><Link href="/">Mağazaya dön ↗</Link></aside>
    <main>{message ? <div className="admin-message">{message}</div> : null}
      {tab === "products" ? <>
        <header><span>KATALOG YÖNETİMİ</span><h1>Ürünler ve fiyatlar</h1><p>Fiyat, stok, Google ürün kategorisi ve ürün görsellerini tek yerden yönetin.</p></header>
        <details className="admin-create" open><summary>+ Yeni ürün ekle</summary><form onSubmit={createProduct} className="admin-form-grid"><label>Ürün adı<input name="name" required /></label><label>SKU<input name="sku" required /></label><label>Kategori<input name="category" placeholder="Plise Perde" required /></label><label>URL adı<input name="slug" placeholder="otomatik oluşturulur" /></label><label>Fiyat (₺)<input name="price" type="number" min="0" step="0.01" required /></label><label>İndirimli fiyat (₺)<input name="salePrice" type="number" min="0" step="0.01" /></label><label>Stok<input name="stock" type="number" min="0" required /></label><label>Google ürün kategorisi<input name="googleProductCategory" defaultValue="Home & Garden > Decor > Window Treatments" /></label><label className="span-2">Açıklama<textarea name="description" rows={3} /></label><label>Ürün görseli<input name="image" type="file" accept="image/png,image/jpeg,image/webp" /></label><label className="check"><input name="featured" type="checkbox" /> Öne çıkar</label><button type="submit">Ürünü kaydet</button></form></details>
        <section className="admin-product-list">{products.map((product) => <article key={product.id}><div className="admin-product-image"><Image unoptimized src={product.image} alt={product.name} fill sizes="90px" /></div><div className="admin-product-name"><small>{product.sku} · {product.category}</small><h2>{product.name}</h2><a href={`/urunler/${product.slug}`} target="_blank">Ürünü görüntüle ↗</a></div><form onSubmit={(event) => updateProduct(event, product.id)} className="admin-inline-form"><label>Fiyat<input name="price" type="number" step="0.01" defaultValue={(product.price / 100).toFixed(2)} /></label><label>İndirim<input name="salePrice" type="number" step="0.01" defaultValue={product.salePrice ? (product.salePrice / 100).toFixed(2) : ""} /></label><label>Stok<input name="stock" type="number" defaultValue={product.stock} /></label><label>Durum<select name="availability" defaultValue={product.availability}><option value="in_stock">Stokta</option><option value="out_of_stock">Tükendi</option><option value="preorder">Ön sipariş</option><option value="backorder">Tedarik</option></select></label><label className="check"><input name="active" type="checkbox" defaultChecked={Boolean(product.active)} /> Yayında</label><label className="check"><input name="featured" type="checkbox" defaultChecked={Boolean(product.featured)} /> Öne çıkan</label><button type="submit">Güncelle</button></form><form onSubmit={(event) => uploadImage(event, product.id)} className="admin-image-form"><input name="image" type="file" accept="image/png,image/jpeg,image/webp" required /><button type="submit">Yeni görsel yükle</button></form></article>)}</section>
      </> : <>
        <header><span>SİPARİŞ OPERASYONU</span><h1>Siparişler</h1><p>Yeni siparişleri onaylayın; üretim, kargo ve teslimat durumlarını güncelleyin.</p></header>
        <section className="admin-order-list">{orders.length ? orders.map((order) => <article key={order.id}><div><small>{new Date(order.createdAt).toLocaleString("tr-TR")}</small><h2>{order.orderNumber}</h2><p>{order.customerName} · {order.email} · {order.phone}</p><strong>{formatMoney(order.total, order.currency)}</strong></div><span className={`order-status status-${order.status}`}>{statusNames[order.status] ?? order.status}</span><form onSubmit={(event) => updateOrder(event, order.id)}><select name="status" defaultValue={order.status}>{statuses.map((status) => <option key={status} value={status}>{statusNames[status]}</option>)}</select><input name="note" placeholder="Müşteri veya operasyon notu" /><button type="submit">Durumu kaydet</button></form></article>) : <div className="empty-state">Henüz sipariş yok.</div>}</section>
      </>}
    </main>
  </div>;
}
