import type { CatalogProduct } from "./index";

export type SeedProduct = Omit<CatalogProduct, "id"> & { id?: string; rootCategory: string };

export const GENERATED_SEEDS: SeedProduct[] = [
  {
    id: "a2882684-edcf-499a-89f0-8d2cd39b4583",
    name: "Otomatik Kumandalı Pencere Panjuru Antrasit",
    slug: "otomatik-kumandali-pencere-panjuru-antrasit",
    sku: "MRL-B108685E",
    description: "Otomatik Kumandalı Pencere Panjuru Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2755478,
    salePrice: 2041095,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-pencere-pan-5ff214.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-pencere-pan-5ff214.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:50.712Z",
    updatedAt: "2026-09-07T11:37:50.713Z"
  },
  {
    id: "8ce30d7a-e922-4f62-9f6c-0894a189f76e",
    name: "Otomatik Kumandalı Pencere Panjuru Metalik Gri",
    slug: "otomatik-kumandali-pencere-panjuru-metalik-gri",
    sku: "MRL-E338EA09",
    description: "Otomatik Kumandalı Pencere Panjuru Metalik Gri - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2755478,
    salePrice: 2041095,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-pencere-pan-b8c09d.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-pencere-pan-b8c09d.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:50.787Z",
    updatedAt: "2026-09-07T11:37:50.787Z"
  },
  {
    id: "28ed2bab-f802-47e3-a25c-a76e6bc4fa08",
    name: "Otomatik Kumandalı Pencere Panjuru Altınmeşe",
    slug: "otomatik-kumandali-pencere-panjuru-altinmese",
    sku: "MRL-CC40B038",
    description: "Otomatik Kumandalı Pencere Panjuru Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2755478,
    salePrice: 2041095,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-pencere-pan-e93aeb.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-pencere-pan-e93aeb.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:50.859Z",
    updatedAt: "2026-09-07T11:37:50.859Z"
  },
  {
    id: "d1b9a003-9c5d-4d38-b839-9c8b4091e10f",
    name: "Otomatik Kumandalı Pencere Panjuru Beyaz",
    slug: "otomatik-kumandali-pencere-panjuru-beyaz",
    sku: "MRL-6FFA41F9",
    description: "Otomatik Kumandalı Pencere Panjuru Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2755478,
    salePrice: 2041095,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-pencere-pan-984edd.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-pencere-pan-984edd.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:50.935Z",
    updatedAt: "2026-09-07T11:37:50.935Z"
  },
  {
    id: "3701b37a-46b5-4e68-b0e9-b6b90b8c007a",
    name: "Otomatik Kumandalı Kapı Panjuru Antrasit",
    slug: "otomatik-kumandali-kapi-panjuru-antrasit",
    sku: "MRL-6E79B2BB",
    description: "Otomatik Kumandalı Kapı Panjuru Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2793930,
    salePrice: 2069578,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Kapı Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-kapi-panjur-943a42.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-kapi-panjur-943a42.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.008Z",
    updatedAt: "2026-09-07T11:37:51.008Z"
  },
  {
    id: "9c41733c-b0c7-473f-af9c-3be45792cba5",
    name: "Otomatik Kumandalı Kapı Panjuru Metalik Gri",
    slug: "otomatik-kumandali-kapi-panjuru-metalik-gri",
    sku: "MRL-5C3A9151",
    description: "Otomatik Kumandalı Kapı Panjuru Metalik Gri - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2793930,
    salePrice: 2069578,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Kapı Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-kapi-panjur-fe1d0f.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-kapi-panjur-fe1d0f.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.084Z",
    updatedAt: "2026-09-07T11:37:51.084Z"
  },
  {
    id: "baf4d0c6-2197-4f6e-8032-08b38868091c",
    name: "Otomatik Kumandalı Kapı Panjuru Altınmeşe",
    slug: "otomatik-kumandali-kapi-panjuru-altinmese",
    sku: "MRL-423722B1",
    description: "Otomatik Kumandalı Kapı Panjuru Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2793930,
    salePrice: 2069578,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Kapı Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-kapi-panjur-f07a1a.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-kapi-panjur-f07a1a.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.159Z",
    updatedAt: "2026-09-07T11:37:51.159Z"
  },
  {
    id: "e74c85dc-6d8d-4bd5-aa4d-9e8c920d0ff1",
    name: "Otomatik Kumandalı Kapı Panjuru Beyaz",
    slug: "otomatik-kumandali-kapi-panjuru-beyaz",
    sku: "MRL-8C273A41",
    description: "Otomatik Kumandalı Kapı Panjuru Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 2793930,
    salePrice: 2069578,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Kapı Panjurları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-kapi-panjur-28270e.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-kapi-panjur-28270e.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.241Z",
    updatedAt: "2026-09-07T11:37:51.241Z"
  },
  {
    id: "fe184f9d-4065-44da-bacb-a5d40d1c7741",
    name: "Otomatik Kumandalı Sürme Kapı Panjuru Beyaz",
    slug: "otomatik-kumandali-surme-kapi-panjuru-beyaz",
    sku: "MRL-941AEAF3",
    description: "Otomatik Kumandalı Sürme Kapı Panjuru Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 3365476,
    salePrice: 2492945,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Maximum Kapı",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-surme-kapi--cf98e0.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-surme-kapi--cf98e0.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.321Z",
    updatedAt: "2026-09-07T11:37:51.321Z"
  },
  {
    id: "f576e6f9-244e-4f4d-911e-25a5a598f034",
    name: "Otomatik Kumandalı Sürme Kapı Panjuru Antrasit",
    slug: "otomatik-kumandali-surme-kapi-panjuru-antrasit",
    sku: "MRL-FAFA5714",
    description: "Otomatik Kumandalı Sürme Kapı Panjuru Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 3365476,
    salePrice: 2492945,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Maximum Kapı",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-surme-kapi--3fbd9a.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-surme-kapi--3fbd9a.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:51.393Z",
    updatedAt: "2026-09-07T11:37:51.393Z"
  },
  {
    id: "d62b9ee0-c921-42bf-8128-df717d98ba15",
    name: "Otomatik Kumandalı Sürme Kapı Panjuru Altınmeşe",
    slug: "otomatik-kumandali-surme-kapi-panjuru-altinmese",
    sku: "MRL-5E3107E5",
    description: "Otomatik Kumandalı Sürme Kapı Panjuru Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 3365476,
    salePrice: 2492945,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Maximum Kapı",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-surme-kapi--0956ac.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-surme-kapi--0956ac.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:53.607Z",
    updatedAt: "2026-09-07T11:37:53.607Z"
  },
  {
    id: "b466d554-ded4-4a72-9874-5fa6e612118d",
    name: "Otomatik Kumandalı Sürme Kapı Panjuru Metalik Gri",
    slug: "otomatik-kumandali-surme-kapi-panjuru-metalik-gri",
    sku: "MRL-24EE1A21",
    description: "Otomatik Kumandalı Sürme Kapı Panjuru Metalik Gri - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 3952753,
    salePrice: 2927965,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Maximum Kapı",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-surme-kapi--86cb96.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-surme-kapi--86cb96.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:53.676Z",
    updatedAt: "2026-09-07T11:37:53.676Z"
  },
  {
    id: "4ef2aa73-0567-4866-9d52-368f4b37d2a7",
    name: "Orjin Seperatör Sürme Beyaz Profil Akordiyon Perdeli Kapı, İstediğiniz Ölçüde, (Max. 110x240) 5 Farklı Renk Seçeneği",
    slug: "orjin-seperator-surme-beyaz-profil-akordiyon-perdeli-kapi-istediginiz-olcude-max-110x240-5-farkli-renk-secenegi",
    sku: "MRL-6A72A5EB",
    description: "Orjin Seperatör Sürme Beyaz Profil Akordiyon Perdeli Kapı, İstediğiniz Ölçüde, (Max. 110x240) 5 Farklı Renk Seçeneği - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 439425,
    salePrice: 325500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Seperatör Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/orjin-seperator-surme-beyaz-pr-139672.webp",
    images: [
      "/images/products/kamatas/orjin-seperator-surme-beyaz-pr-139672.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:53.954Z",
    updatedAt: "2026-09-07T11:37:53.954Z"
  },
  {
    id: "7f7268ac-a225-4f02-9264-77ca53e649f8",
    name: "Orjin Seperatör Antrasit Profil Sürme Akordiyon Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde",
    slug: "orjin-seperator-antrasit-profil-surme-akordiyon-perdeli-kapi-max-110x240-istediginiz-olcude",
    sku: "MRL-264EF13E",
    description: "Orjin Seperatör Antrasit Profil Sürme Akordiyon Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 439425,
    salePrice: 325500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Seperatör Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/orjin-seperator-antrasit-profi-8981f0.webp",
    images: [
      "/images/products/kamatas/orjin-seperator-antrasit-profi-8981f0.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.035Z",
    updatedAt: "2026-09-07T11:37:54.035Z"
  },
  {
    id: "fd0acbe1-8696-4e95-beba-b1c1023eaf83",
    name: "Orjin Seperatör Kahverengi Profil Sürme Akordiyon Perdeli Kapı, İstediğiniz Ölçüde, (Max: 110x240) 5 Farklı Renk Seçeneği",
    slug: "orjin-seperator-kahverengi-profil-surme-akordiyon-perdeli-kapi-istediginiz-olcude-max-110x240-5-farkli-renk-secenegi",
    sku: "MRL-72AF098D",
    description: "Orjin Seperatör Kahverengi Profil Sürme Akordiyon Perdeli Kapı, İstediğiniz Ölçüde, (Max: 110x240) 5 Farklı Renk Seçeneği - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 564300,
    salePrice: 418000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Seperatör Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/orjin-seperator-kahverengi-pro-a07378.webp",
    images: [
      "/images/products/kamatas/orjin-seperator-kahverengi-pro-a07378.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.113Z",
    updatedAt: "2026-09-07T11:37:54.113Z"
  },
  {
    id: "ce6f6d57-3b91-49ba-a589-135e594fcc1e",
    name: "%100 Işık Yalıtımlı Plise Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde Antrasit Profil",
    slug: "100-isik-yalitimli-plise-perdeli-kapi-max-110x240-istediginiz-olcude-antrasit-profil",
    sku: "MRL-F39AAAC6",
    description: "%100 Işık Yalıtımlı Plise Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde Antrasit Profil - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 696024,
    salePrice: 515573,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "%100 Işık Yalıtımlı Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/100-isik-yalitimli-plise-perde-ef9ece.webp",
    images: [
      "/images/products/kamatas/100-isik-yalitimli-plise-perde-ef9ece.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.186Z",
    updatedAt: "2026-09-07T11:37:54.187Z"
  },
  {
    id: "0e4c9c4d-e92a-427c-82de-68ac326a5d8c",
    name: "%100 Işık Yalıtımlı Sürme Plise Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde Beyaz Profil",
    slug: "100-isik-yalitimli-surme-plise-perdeli-kapi-max-110x240-istediginiz-olcude-beyaz-profil",
    sku: "MRL-D51F8479",
    description: "%100 Işık Yalıtımlı Sürme Plise Perdeli Kapı, (Max. 110x240) İstediğiniz Ölçüde Beyaz Profil - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 696024,
    salePrice: 515573,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "%100 Işık Yalıtımlı Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/100-isik-yalitimli-surme-plise-1d283e.webp",
    images: [
      "/images/products/kamatas/100-isik-yalitimli-surme-plise-1d283e.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.262Z",
    updatedAt: "2026-09-07T11:37:54.262Z"
  },
  {
    id: "0990f944-7205-4b7f-90bf-1ec19b39792a",
    name: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Beyaz Profil, İstediğiniz Ölçüde (Max 110x240)",
    slug: "termal-100-isi-ve-isik-yalitimli-seperator-surme-akordiyon-perdeli-kapi-beyaz-profil-istediginiz-olcude-max-110x240",
    sku: "MRL-EDD34F86",
    description: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Beyaz Profil, İstediğiniz Ölçüde (Max 110x240) - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1007775,
    salePrice: 746500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Termal %100 Isı ve Işık Yalıtımlı Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-889967.webp",
    images: [
      "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-889967.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.343Z",
    updatedAt: "2026-09-07T11:37:54.343Z"
  },
  {
    id: "53ac0171-2c2e-4462-a94b-20e681a8b923",
    name: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Antrasit Profil, İstediğiniz Ölçüde (Max 110x240)",
    slug: "termal-100-isi-ve-isik-yalitimli-seperator-surme-akordiyon-perdeli-kapi-antrasit-profil-istediginiz-olcude-max-110x240",
    sku: "MRL-7EE8AA82",
    description: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Antrasit Profil, İstediğiniz Ölçüde (Max 110x240) - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1007775,
    salePrice: 746500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Termal %100 Isı ve Işık Yalıtımlı Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-8f6823.webp",
    images: [
      "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-8f6823.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.424Z",
    updatedAt: "2026-09-07T11:37:54.424Z"
  },
  {
    id: "f34fa6c8-65a6-4d4a-b230-29f1dfec1943",
    name: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Kahverengi Profil, İstediğiniz Ölçüde (Max 110x240)",
    slug: "termal-100-isi-ve-isik-yalitimli-seperator-surme-akordiyon-perdeli-kapi-kahverengi-profil-istediginiz-olcude-max-110x240",
    sku: "MRL-F4E6B839",
    description: "Termal %100 Isı ve Işık Yalıtımlı Seperatör Sürme Akordiyon Perdeli Kapı Kahverengi Profil, İstediğiniz Ölçüde (Max 110x240) - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1007775,
    salePrice: 746500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Termal %100 Isı ve Işık Yalıtımlı Kapılar",
    rootCategory: "Separatör Kapı",
    image: "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-82b56e.webp",
    images: [
      "/images/products/kamatas/termal-100-isi-ve-isik-yalitim-82b56e.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:54.505Z",
    updatedAt: "2026-09-07T11:37:54.505Z"
  },
  {
    id: "2d7179b8-a03f-42af-bba5-0a26f58e21f6",
    name: "Merdiven Tutamağı Bronz 100cm",
    slug: "merdiven-tutamagi-bronz-100cm",
    sku: "MRL-9AEA129D",
    description: "Merdiven Tutamağı Bronz 100cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 196983,
    salePrice: 145913,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-bronz-100cm-6849b0.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-bronz-100cm-6849b0.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:57.706Z",
    updatedAt: "2026-09-07T11:37:57.706Z"
  },
  {
    id: "04f4983d-a352-4a43-a322-4ae5a62e585b",
    name: "Merdiven Tutamağı Bronz 200cm",
    slug: "merdiven-tutamagi-bronz-200cm",
    sku: "MRL-0EC24B2F",
    description: "Merdiven Tutamağı Bronz 200cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 274367,
    salePrice: 203235,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-bronz-200cm-7a1e0c.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-bronz-200cm-7a1e0c.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:57.781Z",
    updatedAt: "2026-09-07T11:37:57.781Z"
  },
  {
    id: "9fc5a689-83b7-4d70-9bb6-1f7481dc78b0",
    name: "Merdiven Tutamağı Metalik Gri 100cm",
    slug: "merdiven-tutamagi-metalik-gri-100cm",
    sku: "MRL-4444CA93",
    description: "Merdiven Tutamağı Metalik Gri 100cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 196983,
    salePrice: 145913,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-metalik-gri--f38eed.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-metalik-gri--f38eed.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:57.855Z",
    updatedAt: "2026-09-07T11:37:57.855Z"
  },
  {
    id: "403c6e6d-b4cc-4d03-826f-64748c7a024f",
    name: "Merdiven Tutamağı Metalik Gri 150cm",
    slug: "merdiven-tutamagi-metalik-gri-150cm",
    sku: "MRL-CA72454A",
    description: "Merdiven Tutamağı Metalik Gri 150cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 246228,
    salePrice: 182391,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-metalik-gri--c38bdb.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-metalik-gri--c38bdb.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:57.926Z",
    updatedAt: "2026-09-07T11:37:57.926Z"
  },
  {
    id: "d369cc4a-75f6-4054-8305-5d6a6dff2e4e",
    name: "Merdiven Tutamağı Metalik Gri 250cm",
    slug: "merdiven-tutamagi-metalik-gri-250cm",
    sku: "MRL-AF2EF1C2",
    description: "Merdiven Tutamağı Metalik Gri 250cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 302508,
    salePrice: 224080,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-metalik-gri--449253.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-metalik-gri--449253.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:57.999Z",
    updatedAt: "2026-09-07T11:37:57.999Z"
  },
  {
    id: "b3812c4a-3c97-4db7-88d3-e50b4f677385",
    name: "Merdiven Tutamağı Metalik Gri 200cm",
    slug: "merdiven-tutamagi-metalik-gri-200cm",
    sku: "MRL-C920763D",
    description: "Merdiven Tutamağı Metalik Gri 200cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 274367,
    salePrice: 203235,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-metalik-gri--3584d2.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-metalik-gri--3584d2.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.076Z",
    updatedAt: "2026-09-07T11:37:58.076Z"
  },
  {
    id: "93195dd8-5f1c-4687-ba6b-761952cd7eb0",
    name: "Merdiven Tutamağı Bronz 250cm",
    slug: "merdiven-tutamagi-bronz-250cm",
    sku: "MRL-05B4B17A",
    description: "Merdiven Tutamağı Bronz 250cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 302508,
    salePrice: 224080,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-bronz-250cm-9f43e3.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-bronz-250cm-9f43e3.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.152Z",
    updatedAt: "2026-09-07T11:37:58.152Z"
  },
  {
    id: "db08a774-b99d-4277-b9a5-0d15ca1d1c2d",
    name: "Merdiven Tutamağı Bronz 150cm",
    slug: "merdiven-tutamagi-bronz-150cm",
    sku: "MRL-2D3706AF",
    description: "Merdiven Tutamağı Bronz 150cm - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 246228,
    salePrice: 182391,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Merdiven Tutamakları",
    rootCategory: "Tutamaklar",
    image: "/images/products/kamatas/merdiven-tutamagi-bronz-150cm-7aa0bd.webp",
    images: [
      "/images/products/kamatas/merdiven-tutamagi-bronz-150cm-7aa0bd.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.227Z",
    updatedAt: "2026-09-07T11:37:58.227Z"
  },
  {
    id: "32fcddb0-224e-4f25-b74d-a8bfc76435d7",
    name: "17*25 Sineklik Aksesuar Takımı Beya",
    slug: "1725-sineklik-aksesuar-takimi-beya",
    sku: "MRL-1CB940C3",
    description: "17*25 Sineklik Aksesuar Takımı Beya - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 23639,
    salePrice: 17510,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-aksesuar-takimi--e02e26.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-aksesuar-takimi--e02e26.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.466Z",
    updatedAt: "2026-09-07T11:37:58.466Z"
  },
  {
    id: "bfdfb9a8-b2bd-4ff4-9c56-7232baa7e779",
    name: "17*25 Sineklik Aksesuar Takımı Siyah",
    slug: "1725-sineklik-aksesuar-takimi-siyah",
    sku: "MRL-FCC5FEA1",
    description: "17*25 Sineklik Aksesuar Takımı Siyah - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 23639,
    salePrice: 17510,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-aksesuar-takimi--48e5bd.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-aksesuar-takimi--48e5bd.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.548Z",
    updatedAt: "2026-09-07T11:37:58.548Z"
  },
  {
    id: "7395c750-e64d-4cd2-9879-80a95ca22147",
    name: "17*25 Sineklik Bağlama 4lü Papuç Beyaz 5 Takım",
    slug: "1725-sineklik-baglama-4lu-papuc-beyaz-5-takim",
    sku: "MRL-FF4B452A",
    description: "17*25 Sineklik Bağlama 4lü Papuç Beyaz 5 Takım - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-baglama-4lu-papu-b46000.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-baglama-4lu-papu-b46000.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.621Z",
    updatedAt: "2026-09-07T11:37:58.621Z"
  },
  {
    id: "8ef0efdf-4968-4449-970c-061e9f5cf73c",
    name: "17*25 Sineklik Bağlama 4lü Papuç Siyah 5 takım",
    slug: "1725-sineklik-baglama-4lu-papuc-siyah-5-takim",
    sku: "MRL-168B8C6E",
    description: "17*25 Sineklik Bağlama 4lü Papuç Siyah 5 takım - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-baglama-4lu-papu-d627df.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-baglama-4lu-papu-d627df.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.699Z",
    updatedAt: "2026-09-07T11:37:58.699Z"
  },
  {
    id: "693de843-8921-4977-9ac6-5bdf7e052b03",
    name: "17*25 Sineklik Köşe Takozu Siyah 8 Adet",
    slug: "1725-sineklik-kose-takozu-siyah-8-adet",
    sku: "MRL-6650CEC3",
    description: "17*25 Sineklik Köşe Takozu Siyah 8 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-kose-takozu-siya-b5d633.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-kose-takozu-siya-b5d633.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.776Z",
    updatedAt: "2026-09-07T11:37:58.776Z"
  },
  {
    id: "6b76c5a2-20a4-4eb5-8771-80d79c6a5044",
    name: "17*25 Sineklik Köşe Takozu Beyaz 8 Adet",
    slug: "1725-sineklik-kose-takozu-beyaz-8-adet",
    sku: "MRL-E6668BDD",
    description: "17*25 Sineklik Köşe Takozu Beyaz 8 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-kose-takozu-beya-15e15f.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-kose-takozu-beya-15e15f.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.856Z",
    updatedAt: "2026-09-07T11:37:58.856Z"
  },
  {
    id: "281d1f6a-7df4-49ae-9dd2-ebb21cdf671b",
    name: "17*25 Sineklik Menteşe Beyaz 8 Adet",
    slug: "1725-sineklik-mentese-beyaz-8-adet",
    sku: "MRL-BAC8DA21",
    description: "17*25 Sineklik Menteşe Beyaz 8 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-mentese-beyaz-8--2aa8c7.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-mentese-beyaz-8--2aa8c7.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:58.929Z",
    updatedAt: "2026-09-07T11:37:58.929Z"
  },
  {
    id: "922cef1d-79dc-4b93-a56f-159e7e7755b1",
    name: "17*25 Sineklik Menteşe Siyah 8 Adet",
    slug: "1725-sineklik-mentese-siyah-8-adet",
    sku: "MRL-8ED00F6D",
    description: "17*25 Sineklik Menteşe Siyah 8 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-mentese-siyah-8--957542.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-mentese-siyah-8--957542.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:59.008Z",
    updatedAt: "2026-09-07T11:37:59.008Z"
  },
  {
    id: "004aa13c-8137-4ef8-a455-b8db62701b8d",
    name: "17*25 Sineklik Tutamak Beyaz 4 Adet",
    slug: "1725-sineklik-tutamak-beyaz-4-adet",
    sku: "MRL-C996CF99",
    description: "17*25 Sineklik Tutamak Beyaz 4 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 16884,
    salePrice: 12507,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere ve Kapı Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-tutamak-beyaz-4--d39d91.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-tutamak-beyaz-4--d39d91.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:59.081Z",
    updatedAt: "2026-09-07T11:37:59.081Z"
  },
  {
    id: "95875600-0ad9-4c89-92f6-b6ad23aaf934",
    name: "17*25 Sineklik Tutamak Siyah 4 Adet",
    slug: "1725-sineklik-tutamak-siyah-4-adet",
    sku: "MRL-61CFAB57",
    description: "17*25 Sineklik Tutamak Siyah 4 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21950,
    salePrice: 16259,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Pencere ve Kapı Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/1725-sineklik-tutamak-siyah-4--00eca5.webp",
    images: [
      "/images/products/kamatas/1725-sineklik-tutamak-siyah-4--00eca5.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:59.158Z",
    updatedAt: "2026-09-07T11:37:59.158Z"
  },
  {
    id: "aaf4c673-57bd-4af8-bc0a-d3422886b4a4",
    name: "Pencere Sineklik Fiberglass Değişim Tülü 80x150 & 4m Sineklik Fitili",
    slug: "pencere-sineklik-fiberglass-degisim-tulu-80x150-4m-sineklik-fitili",
    sku: "MRL-A808BB20",
    description: "Pencere Sineklik Fiberglass Değişim Tülü 80x150 & 4m Sineklik Fitili - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 38694,
    salePrice: 28662,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Tülleri",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/pencere-sineklik-fiberglass-de-3e4615.webp",
    images: [
      "/images/products/kamatas/pencere-sineklik-fiberglass-de-3e4615.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:59.704Z",
    updatedAt: "2026-09-07T11:37:59.704Z"
  },
  {
    id: "f15f418d-59b9-4de8-be66-7ac4f8539d6f",
    name: "Kapı Sineklik Fiberglas Değişim Tülü 100x230 & 6m Sineklik Fitili",
    slug: "kapi-sineklik-fiberglas-degisim-tulu-100x230-6m-sineklik-fitili",
    sku: "MRL-B6EB7550",
    description: "Kapı Sineklik Fiberglas Değişim Tülü 100x230 & 6m Sineklik Fitili - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 51355,
    salePrice: 38041,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Tülleri",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/kapi-sineklik-fiberglas-degisi-6cbf23.webp",
    images: [
      "/images/products/kamatas/kapi-sineklik-fiberglas-degisi-6cbf23.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:37:59.804Z",
    updatedAt: "2026-09-07T11:37:59.805Z"
  },
  {
    id: "35715f03-0987-4fc1-9096-617253d94adc",
    name: "Kedi Tülü Yırtılmaz (Ped Tül)  (EN: 80 CM x150 CM) & + 4m Fitil",
    slug: "kedi-tulu-yirtilmaz-ped-tul-en-80-cm-x150-cm-4m-fitil",
    sku: "MRL-146E80FB",
    description: "Kedi Tülü Yırtılmaz (Ped Tül)  (EN: 80 CM x150 CM) & + 4m Fitil - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 73867,
    salePrice: 54716,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Yırtılmaz Kedi Tülleri",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/kedi-tulu-yirtilmaz-ped-tul-en-e55ef3.webp",
    images: [
      "/images/products/kamatas/kedi-tulu-yirtilmaz-ped-tul-en-e55ef3.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.010Z",
    updatedAt: "2026-09-07T11:38:00.010Z"
  },
  {
    id: "f146d649-a855-49ac-8ebb-d9e1f2c84494",
    name: "Yırtılmaz Kapı Kedi Tülü (Ped Tül)  (En: 100 cm x Boy:230 cm) & + 6m Fitil",
    slug: "yirtilmaz-kapi-kedi-tulu-ped-tul-en-100-cm-x-boy230-cm-6m-fitil",
    sku: "MRL-4C163BBF",
    description: "Yırtılmaz Kapı Kedi Tülü (Ped Tül)  (En: 100 cm x Boy:230 cm) & + 6m Fitil - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 136500,
    salePrice: 101111,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Yırtılmaz Kedi Tülleri",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/yirtilmaz-kapi-kedi-tulu-ped-t-479127.webp",
    images: [
      "/images/products/kamatas/yirtilmaz-kapi-kedi-tulu-ped-t-479127.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.110Z",
    updatedAt: "2026-09-07T11:38:00.110Z"
  },
  {
    id: "ac8adee7-7a7b-453a-a3df-4db0bd7cdf36",
    name: "Alüminyum Duvar L Ayak Kısa Korkuluk Küpeşte Boru Tutucu Parlak 2 ADET",
    slug: "aluminyum-duvar-l-ayak-kisa-korkuluk-kupeste-boru-tutucu-parlak-2-adet",
    sku: "MRL-9C54899B",
    description: "Alüminyum Duvar L Ayak Kısa Korkuluk Küpeşte Boru Tutucu Parlak 2 ADET - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21273,
    salePrice: 15758,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/aluminyum-duvar-l-ayak-kisa-ko-29af51.webp",
    images: [
      "/images/products/kamatas/aluminyum-duvar-l-ayak-kisa-ko-29af51.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.289Z",
    updatedAt: "2026-09-07T11:38:00.289Z"
  },
  {
    id: "416cb72f-5488-4962-b3d8-ca414b8bba2c",
    name: "Alüminyum Duvar L Ayak Kısa Korkuluk Küpeşte Boru Tutucu Bronz 2 ADET",
    slug: "aluminyum-duvar-l-ayak-kisa-korkuluk-kupeste-boru-tutucu-bronz-2-adet",
    sku: "MRL-87820983",
    description: "Alüminyum Duvar L Ayak Kısa Korkuluk Küpeşte Boru Tutucu Bronz 2 ADET - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 21273,
    salePrice: 15758,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/aluminyum-duvar-l-ayak-kisa-ko-c69265.webp",
    images: [
      "/images/products/kamatas/aluminyum-duvar-l-ayak-kisa-ko-c69265.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.367Z",
    updatedAt: "2026-09-07T11:38:00.367Z"
  },
  {
    id: "341ff425-9a08-48c6-aa53-9623dd64080b",
    name: "Aykim Sürme Sineklik Makaralı Makarasız Takoz Takımı Siyah 4 Adet",
    slug: "aykim-surme-sineklik-makarali-makarasiz-takoz-takimi-siyah-4-adet",
    sku: "MRL-26AFBD36",
    description: "Aykim Sürme Sineklik Makaralı Makarasız Takoz Takımı Siyah 4 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 42212,
    salePrice: 31268,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/aykim-surme-sineklik-makarali--fc34d6.webp",
    images: [
      "/images/products/kamatas/aykim-surme-sineklik-makarali--fc34d6.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.440Z",
    updatedAt: "2026-09-07T11:38:00.440Z"
  },
  {
    id: "d09b983e-b971-47d3-a321-a5d600f4d144",
    name: "Aykim Sürme Sineklik Rulmanlı Rulmansız Makaralı Takım Beyaz 4 Adet",
    slug: "aykim-surme-sineklik-rulmanli-rulmansiz-makarali-takim-beyaz-4-adet",
    sku: "MRL-8BFDC683",
    description: "Aykim Sürme Sineklik Rulmanlı Rulmansız Makaralı Takım Beyaz 4 Adet - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 42212,
    salePrice: 31268,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Sineklik Aksesuarları",
    rootCategory: "Aksesuarlar",
    image: "/images/products/kamatas/aykim-surme-sineklik-rulmanli--ed62aa.webp",
    images: [
      "/images/products/kamatas/aykim-surme-sineklik-rulmanli--ed62aa.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.516Z",
    updatedAt: "2026-09-07T11:38:00.516Z"
  },
  {
    id: "705e1132-d6eb-4260-9817-e1f9dc158fe2",
    name: "Akordeon Kapı Sineklik Altınmeşe",
    slug: "akordeon-kapi-sineklik-altinmese",
    sku: "MRL-F413B242",
    description: "Akordeon Kapı Sineklik Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 438750,
    salePrice: 325000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-kapi-sineklik-altinme-805a43.webp",
    images: [
      "/images/products/kamatas/akordeon-kapi-sineklik-altinme-805a43.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.794Z",
    updatedAt: "2026-09-07T11:38:00.794Z"
  },
  {
    id: "f5203114-bba2-4a8f-8131-b566a9c980bd",
    name: "Akordeon Pencere Sineklik Antrasit",
    slug: "akordeon-pencere-sineklik-antrasit",
    sku: "MRL-266A552C",
    description: "Akordeon Pencere Sineklik Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 203364,
    salePrice: 150640,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-pencere-sineklik-antr-c01323.webp",
    images: [
      "/images/products/kamatas/akordeon-pencere-sineklik-antr-c01323.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:00.897Z",
    updatedAt: "2026-09-07T11:38:00.897Z"
  },
  {
    id: "72d851ef-b77e-4698-8372-53c2558d5155",
    name: "Akordeon Pencere Sineklik Altınmeşe",
    slug: "akordeon-pencere-sineklik-altinmese",
    sku: "MRL-4F62F88A",
    description: "Akordeon Pencere Sineklik Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 264415,
    salePrice: 195863,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-pencere-sineklik-alti-050eaa.webp",
    images: [
      "/images/products/kamatas/akordeon-pencere-sineklik-alti-050eaa.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.017Z",
    updatedAt: "2026-09-07T11:38:01.017Z"
  },
  {
    id: "2b5b36c4-65dd-4443-ad9c-3c56dd073e30",
    name: "Akordeon Pencere Sineklik Beyaz",
    slug: "akordeon-pencere-sineklik-beyaz",
    sku: "MRL-6C058513",
    description: "Akordeon Pencere Sineklik Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 203364,
    salePrice: 150640,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-pencere-sineklik-beya-5f93b3.webp",
    images: [
      "/images/products/kamatas/akordeon-pencere-sineklik-beya-5f93b3.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.088Z",
    updatedAt: "2026-09-07T11:38:01.088Z"
  },
  {
    id: "340e67a6-6f34-4a3e-b913-d1000cfeba2e",
    name: "Akordeon Kapı Sineklik Antrasit",
    slug: "akordeon-kapi-sineklik-antrasit",
    sku: "MRL-E0BDAA8C",
    description: "Akordeon Kapı Sineklik Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 337500,
    salePrice: 250000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-kapi-sineklik-antrasi-245c2d.webp",
    images: [
      "/images/products/kamatas/akordeon-kapi-sineklik-antrasi-245c2d.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.161Z",
    updatedAt: "2026-09-07T11:38:01.161Z"
  },
  {
    id: "80b34505-ec63-45c1-b9a3-c00c7004339f",
    name: "Akordeon Kapı Sineklik Beyaz",
    slug: "akordeon-kapi-sineklik-beyaz",
    sku: "MRL-EA1DB402",
    description: "Akordeon Kapı Sineklik Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 337500,
    salePrice: 250000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Akordiyon Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/akordeon-kapi-sineklik-beyaz-83a443.webp",
    images: [
      "/images/products/kamatas/akordeon-kapi-sineklik-beyaz-83a443.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.233Z",
    updatedAt: "2026-09-07T11:38:01.233Z"
  },
  {
    id: "f97e6f09-fbe9-4a9d-9339-1f6a096464cd",
    name: "Menteşeli Kapı Sineklik Altınmeşe",
    slug: "menteseli-kapi-sineklik-altinmese",
    sku: "MRL-3610F3A1",
    description: "Menteşeli Kapı Sineklik Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 189675,
    salePrice: 140500,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/menteseli-kapi-sineklik-altinm-821ef4.webp",
    images: [
      "/images/products/kamatas/menteseli-kapi-sineklik-altinm-821ef4.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.303Z",
    updatedAt: "2026-09-07T11:38:01.303Z"
  },
  {
    id: "4ec40394-e0a3-4cc3-ba69-52301be2997b",
    name: "Menteşeli Kapı Sineklik Antrasit",
    slug: "menteseli-kapi-sineklik-antrasit",
    sku: "MRL-ED45CEFA",
    description: "Menteşeli Kapı Sineklik Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 157950,
    salePrice: 117000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/menteseli-kapi-sineklik-antras-9e5033.webp",
    images: [
      "/images/products/kamatas/menteseli-kapi-sineklik-antras-9e5033.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.376Z",
    updatedAt: "2026-09-07T11:38:01.376Z"
  },
  {
    id: "9e244146-6cbb-4fb2-89df-e42a554ee9ac",
    name: "Menteşeli Pencere Sineklik Altınmeşe",
    slug: "menteseli-pencere-sineklik-altinmese",
    sku: "MRL-829DB020",
    description: "Menteşeli Pencere Sineklik Altınmeşe - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 121500,
    salePrice: 90000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/menteseli-pencere-sineklik-alt-d69f4f.webp",
    images: [
      "/images/products/kamatas/menteseli-pencere-sineklik-alt-d69f4f.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.450Z",
    updatedAt: "2026-09-07T11:38:01.450Z"
  },
  {
    id: "1bd54fb1-3436-4c15-ac7a-d55cbc9f3e71",
    name: "KEDİ Tüllü Menteşeli KAPI Sineklik Beyaz",
    slug: "kedi-tullu-menteseli-kapi-sineklik-beyaz",
    sku: "MRL-432F026E",
    description: "KEDİ Tüllü Menteşeli KAPI Sineklik Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 206550,
    salePrice: 153000,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/kedi-tullu-menteseli-kapi-sine-96728a.webp",
    images: [
      "/images/products/kamatas/kedi-tullu-menteseli-kapi-sine-96728a.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.525Z",
    updatedAt: "2026-09-07T11:38:01.525Z"
  },
  {
    id: "791d6f80-c329-4d04-9dfa-25705f636b33",
    name: "Menteşeli Pencere Sineklik  Antrasit",
    slug: "menteseli-pencere-sineklik-antrasit",
    sku: "MRL-8AE715ED",
    description: "Menteşeli Pencere Sineklik  Antrasit - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 94365,
    salePrice: 69900,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/menteseli-pencere-sineklik-ant-ff2376.webp",
    images: [
      "/images/products/kamatas/menteseli-pencere-sineklik-ant-ff2376.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.723Z",
    updatedAt: "2026-09-07T11:38:01.723Z"
  },
  {
    id: "ec8963fc-91ea-4f91-aa03-c684f3302c3a",
    name: "Menteşeli Pencere Sineklik Beyaz",
    slug: "menteseli-pencere-sineklik-beyaz",
    sku: "MRL-936B83E5",
    description: "Menteşeli Pencere Sineklik Beyaz - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 94365,
    salePrice: 69900,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Menteşeli Sineklikler",
    rootCategory: "Sineklikler",
    image: "/images/products/kamatas/menteseli-pencere-sineklik-bey-99daf8.webp",
    images: [
      "/images/products/kamatas/menteseli-pencere-sineklik-bey-99daf8.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:01.795Z",
    updatedAt: "2026-09-07T11:38:01.795Z"
  },
  {
    id: "157b095d-6d0a-4c71-b334-3c63b4e0ed3a",
    name: "Orjin Pliseli Perde Beyaz, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-beyaz-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-D851D08C",
    description: "Orjin Pliseli Perde Beyaz, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-beyaz-katl-3040a5.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-beyaz-katl-3040a5.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.168Z",
    updatedAt: "2026-09-07T11:38:06.168Z"
  },
  {
    id: "744e3e2a-518f-4673-b338-d1f1dcb53d4a",
    name: "Orjin Pliseli Perde Antrasit, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-antrasit-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-DFBD5CD4",
    description: "Orjin Pliseli Perde Antrasit, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-antrasit-k-21a669.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-antrasit-k-21a669.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.240Z",
    updatedAt: "2026-09-07T11:38:06.240Z"
  },
  {
    id: "b96d8543-7d41-48de-803f-f91f120a5b5e",
    name: "Orjin Pliseli Perde Krem, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-krem-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-044EE627",
    description: "Orjin Pliseli Perde Krem, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-krem-katla-dfa199.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-krem-katla-dfa199.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.312Z",
    updatedAt: "2026-09-07T11:38:06.312Z"
  },
  {
    id: "52c4fbaf-00b8-4589-b958-320de74bd70d",
    name: "Orjin Pliseli Perde Gri, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-gri-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-D1A91FFE",
    description: "Orjin Pliseli Perde Gri, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-gri-katlan-1d8996.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-gri-katlan-1d8996.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.384Z",
    updatedAt: "2026-09-07T11:38:06.384Z"
  },
  {
    id: "9300deee-9206-4fe3-bb04-08e50edc10b6",
    name: "Orjin Pliseli Perde Kahverengi, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-kahverengi-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-71F020AA",
    description: "Orjin Pliseli Perde Kahverengi, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-kahverengi-dcd59e.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-kahverengi-dcd59e.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.460Z",
    updatedAt: "2026-09-07T11:38:06.460Z"
  },
  {
    id: "618034c1-1c48-4b2a-8000-f40143c5d837",
    name: "Bambu Ara Gri Plise Perde",
    slug: "bambu-ara-gri-plise-perde",
    sku: "MRL-DD311362",
    description: "Bambu Ara Gri Plise Perde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1181,
    salePrice: 875,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Bambu Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/bambu-ara-gri-plise-perde-80df54.webp",
    images: [
      "/images/products/kamatas/bambu-ara-gri-plise-perde-80df54.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.549Z",
    updatedAt: "2026-09-07T11:38:06.549Z"
  },
  {
    id: "048af022-d5f9-4f14-801f-f05417711361",
    name: "Bambu Plise Perde Krem",
    slug: "bambu-plise-perde-krem",
    sku: "MRL-D13C9729",
    description: "Bambu Plise Perde Krem - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1181,
    salePrice: 875,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Bambu Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/bambu-plise-perde-krem-d0b510.webp",
    images: [
      "/images/products/kamatas/bambu-plise-perde-krem-d0b510.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.634Z",
    updatedAt: "2026-09-07T11:38:06.634Z"
  },
  {
    id: "822f50ae-6f1a-4583-93d0-09280ae0a2d7",
    name: "Dimout Krem Plise Perde",
    slug: "dimout-krem-plise-perde",
    sku: "MRL-8B5C4CBC",
    description: "Dimout Krem Plise Perde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1328,
    salePrice: 984,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Dimout Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/dimout-krem-plise-perde-87cf2c.webp",
    images: [
      "/images/products/kamatas/dimout-krem-plise-perde-87cf2c.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.708Z",
    updatedAt: "2026-09-07T11:38:06.708Z"
  },
  {
    id: "40d927be-7709-4d5a-8c44-2b24bea078bc",
    name: "Dimout Antrasit Plise Perde",
    slug: "dimout-antrasit-plise-perde",
    sku: "MRL-558407F6",
    description: "Dimout Antrasit Plise Perde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 1328,
    salePrice: 984,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Dimout Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/dimout-antrasit-plise-perde-35fb0d.webp",
    images: [
      "/images/products/kamatas/dimout-antrasit-plise-perde-35fb0d.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.798Z",
    updatedAt: "2026-09-07T11:38:06.798Z"
  },
  {
    id: "9cfd6b0b-6259-44ee-b1a3-d762a06e00a7",
    name: "Orjin Pliseli Perde Kırmızı, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde",
    slug: "orjin-pliseli-perde-kirmizi-katlanir-camevofis-perdesi-istedigin-olcude",
    sku: "MRL-98DA474A",
    description: "Orjin Pliseli Perde Kırmızı, Katlanır Cam/Ev/Ofis Perdesi, İstediğin Ölçüde - Marel yüksek kalite güvencesiyle özel ölçü üretilmektedir.",
    price: 809,
    salePrice: 599,
    currency: "TRY",
    stock: 150,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Orjin Plise Perdeler",
    rootCategory: "Perdeler",
    image: "/images/products/kamatas/orjin-pliseli-perde-kirmizi-ka-f13a05.webp",
    images: [
      "/images/products/kamatas/orjin-pliseli-perde-kirmizi-ka-f13a05.webp"
    ],
    colors: "[\"Beyaz\",\"Antrasit\",\"Krem\",\"Gri\",\"Kahve\"]",
    createdAt: "2026-09-07T11:38:06.877Z",
    updatedAt: "2026-09-07T11:38:06.877Z"
  },
  {
    id: "29599043-b1e5-4e2b-874f-a15397414262",
    name: "Otomatik Panjur Çok Kanallı Uzaktan Kumanda",
    slug: "otomatik-panjur-cok-kanalli-uzaktan-kumanda",
    sku: "MRL-PNJ-KMD01",
    description: "Marel Otomatik Panjur sistemleri için çok kanallı kablosuz uzaktan kumanda.",
    price: 110000,
    salePrice: 75000,
    currency: "TRY",
    stock: 100,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Panjur Aksesuarları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-pencere-pan-ad4f11.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-pencere-pan-ad4f11.webp"
    ],
    colors: "[\"Beyaz\",\"Siyah\"]",
    createdAt: "2026-09-07T11:38:06.877Z",
    updatedAt: "2026-09-07T11:38:06.877Z"
  },
  {
    id: "1d21afa3-bd2d-4640-9505-9e1551ab9e9d",
    name: "Otomatik Panjur Tüp Motor ve Dahili Alıcı Seti",
    slug: "otomatik-panjur-tup-motor-ve-dahili-alici-seti",
    sku: "MRL-PNJ-MTR02",
    description: "Yüksek torklu sessiz çalışma özellikli Marel otomatik panjur motoru ve alıcı seti.",
    price: 450000,
    salePrice: 325000,
    currency: "TRY",
    stock: 100,
    availability: "in_stock",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    category: "Panjur Aksesuarları",
    rootCategory: "Otomatik Panjurlar",
    image: "/images/products/kamatas/otomatik-kumandali-kapi-panjuru-0b3252.webp",
    images: [
      "/images/products/kamatas/otomatik-kumandali-kapi-panjuru-0b3252.webp"
    ],
    colors: "[\"Metalik\"]",
    createdAt: "2026-09-07T11:38:06.877Z",
    updatedAt: "2026-09-07T11:38:06.877Z"
  }
];
