export const GENERATED_SEEDS = [
  {
    id: "prod-dia",
    name: "Diamond Series Plise Perde",
    slug: "diamond-series-plise-perde",
    sku: "PLISE-DIA",
    description: "Özel ölçüye göre üretilen Diamond Serisi plise perde sistemleri. Yüksek kumaş kalitesi, delmeden pratik montaj.",
    price: 55000,
    salePrice: 55000,
    currency: "TRY",
    stock: 100,
    category: "Diamond",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/diamond-series-30-40-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/diamond-series-30-40-karartma-plise-perde.jpg",
      "/images/yaren/diamond100.png",
      "/images/yaren/diamond101.png",
      "/images/yaren/diamond102.png",
      "/images/yaren/diamond108.png"
    ],
    colors: '["Beyaz","Ekru","Gri","Ara-Gri","Vizon","Bej","Krem","Açık Gri","Antrasit","Siyah","Füme","Kahve","Yeşil","Mavi","Kırmızı","Turuncu"]'
  },
  {
    id: "prod-touch",
    name: "Touch Series Plise Perde",
    slug: "touch-series-plise-perde",
    sku: "PLISE-TOUCH",
    description: "Touch Serisi zarif dokusuyla mekanlarınıza modern ve estetik bir hava katar.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Touch",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/yaren/TOUCH-1001.png",
    images: [
      "/images/yaren/TOUCH-1001.png",
      "/images/yaren/TOUCH-1002.png",
      "/images/yaren/TOUCH-1003.png",
      "/images/yaren/TOUCH-1004.png"
    ],
    colors: '["Bej","Gri","Antrasit","Kahve"]'
  },
  {
    id: "prod-new",
    name: "New Series Plise Perde",
    slug: "new-series-plise-perde",
    sku: "PLISE-NEW",
    description: "New Serisi özel ölçü plise perde modelleri.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "New",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/new-series-30-40-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/new-series-30-40-karartma-plise-perde.jpg",
      "/images/yaren/NEW-2001.png",
      "/images/yaren/NEW-2002.png",
      "/images/yaren/NEW-2003.png"
    ],
    colors: '["Bej","Antrasit","Gri","Füme","Bordo"]'
  },
  {
    id: "prod-tulle",
    name: "Tulle Series Plise Perde",
    slug: "tulle-series-plise-perde",
    sku: "PLISE-TULLE",
    description: "Tül plise perde sistemleri ile ferah ve aydınlık yaşam alanları.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Tulle",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/yaren/TULLE-01_-scaled.jpg",
    images: ["/images/yaren/TULLE-01_-scaled.jpg"],
    colors: '["Beyaz","Krem","Gri"]'
  },
  {
    id: "prod-efe",
    name: "Efe Series Plise Perde",
    slug: "efe-series-plise-perde",
    sku: "PLISE-EFE",
    description: "Efe Serisi dayanıklı mekanizma ve modern renk seçenekleri.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Efe",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/efe-series-30-40-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/efe-series-30-40-karartma-plise-perde.jpg",
      "/images/yaren/EFE-3001.png",
      "/images/yaren/EFE-3002.png",
      "/images/yaren/EFE-3003.png"
    ],
    colors: '["Bej","Gri","Antrasit"]'
  },
  {
    id: "prod-ece",
    name: "Ece Series Plise Perde",
    slug: "ece-series-plise-perde",
    sku: "PLISE-ECE",
    description: "Ece Serisi kaliteli kumaş dokusuyla pencerenize tam uyum sağlar.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Ece",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/ece-series-30-40-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/ece-series-30-40-karartma-plise-perde.jpg",
      "/images/yaren/ECE-4001.png",
      "/images/yaren/ECE-4002.png",
      "/images/yaren/ECE-4003.png"
    ],
    colors: '["Bej","Gri","Antrasit"]'
  },
  {
    id: "prod-blackout",
    name: "Blackout Series Plise Perde",
    slug: "blackout-series-plise-perde",
    sku: "PLISE-BLACKOUT",
    description: "Blackout Serisi %100 ışık geçirmez kumaş yapısıyla maksimum karanlık ve mahremiyet sağlar.",
    price: 116600,
    salePrice: 116600,
    currency: "TRY",
    stock: 100,
    category: "Blackout",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/blackout.webp",
    images: [
      "/images/catalog/blackout.webp",
      "/images/yaren/BLACOUT-KREM.png",
      "/images/yaren/BLACOUT-GRI.png",
      "/images/yaren/BLACOUT-ANTRASIT.png",
      "/images/yaren/BLACOUT-SIYAH.png"
    ],
    colors: '["Krem","Gri","Antrasit","Kahve","Siyah"]'
  },
  {
    id: "prod-honeycomb",
    name: "Honeycomb Series Plise Perde",
    slug: "honeycomb-series-plise-perde",
    sku: "PLISE-HONEYCOMB",
    description: "Honeycomb Isı Yalıtımlı petek dokulu hücresel plise perde. Kışın sıcak, yazın serin tutar.",
    price: 116600,
    salePrice: 116600,
    currency: "TRY",
    stock: 100,
    category: "Honeycomb",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/yaren/HONEY-001.png",
    images: [
      "/images/yaren/HONEY-001.png",
      "/images/yaren/HONEY-002.png",
      "/images/yaren/HONEY-003.png",
      "/images/yaren/HONEY-004.png",
      "/images/yaren/HONEY-005.png"
    ],
    colors: '["Beyaz","Krem","Gri","Antrasit","Kahve"]'
  },
  {
    id: "prod-dark",
    name: "Dark Series Plise Perde",
    slug: "dark-series-plise-perde",
    sku: "PLISE-DARK",
    description: "Dark Serisi yüksek oranda ışık kırma özelliği ve modern renk tonları sunar.",
    price: 82500,
    salePrice: 82500,
    currency: "TRY",
    stock: 100,
    category: "Dark",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/dark-series-80-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/dark-series-80-karartma-plise-perde.jpg",
      "/images/yaren/DARK-5001.png",
      "/images/yaren/DARK-5002.png",
      "/images/yaren/DARK-5003.png"
    ],
    colors: '["Antrasit","Krem","Gri","Kahve"]'
  },
  {
    id: "prod-bambu",
    name: "Bambu Series Plise Perde",
    slug: "bambu-series-plise-perde",
    sku: "PLISE-BAMBU",
    description: "Bambu Series doğal ahşap dokusu efektiyle ev ve ofis ortamlarına sıcaklık katar.",
    price: 66000,
    salePrice: 66000,
    currency: "TRY",
    stock: 100,
    category: "Bambu",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/bambu-series-50-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/bambu-series-50-karartma-plise-perde.jpg",
      "/images/yaren/BAMBU-6001.png",
      "/images/yaren/BAMBU-6002.png",
      "/images/yaren/BAMBU-6003.png"
    ],
    colors: '["Açık Gri","Gri","Beyaz","Krem","Vizon","Kahve","Antrasit"]'
  },
  {
    id: "prod-silver",
    name: "Silver Series Plise Perde",
    slug: "silver-series-plise-perde",
    sku: "PLISE-SILVER",
    description: "Silver Serisi arka yüzeyindeki özel kaplama sayesinde UV ışınlarını engeller.",
    price: 77000,
    salePrice: 77000,
    currency: "TRY",
    stock: 100,
    category: "Silver",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/silver-series-70-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/silver-series-70-karartma-plise-perde.jpg",
      "/images/yaren/SILVER-7001.png",
      "/images/yaren/SILVER-7002.png",
      "/images/yaren/SILVER-7003.png"
    ],
    colors: '["Beyaz","Gri","Krem","Antrasit","Siyah"]'
  },
  {
    id: "prod-gold",
    name: "Gold Series Plise Perde",
    slug: "gold-series-plise-perde",
    sku: "PLISE-GOLD",
    description: "Gold Serisi zengin desenli dokusu ve estetik görünümüyle lüks mekanlar için idealdir.",
    price: 77000,
    salePrice: 77000,
    currency: "TRY",
    stock: 100,
    category: "Gold",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 1,
    image: "/images/catalog/gold-series-70-karartma-plise-perde.jpg",
    images: [
      "/images/catalog/gold-series-70-karartma-plise-perde.jpg",
      "/images/yaren/GOLD-8001.png",
      "/images/yaren/GOLD-8002.png",
      "/images/yaren/GOLD-8003.png"
    ],
    colors: '["Gri","Beyaz","Krem","Vizon","Antrasit"]'
  },
  {
    id: "prod-arda",
    name: "Arda Series Plise Perde",
    slug: "arda-series-plise-perde",
    sku: "PLISE-ARDA",
    description: "Arda Serisi modern plise perde modelleri.",
    price: 55000,
    salePrice: 55000,
    currency: "TRY",
    stock: 100,
    category: "Arda",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 0,
    image: "/images/products/arda/arda 1.png",
    images: ["/images/products/arda/arda 1.png", "/images/products/arda/arda 2.png"],
    colors: '["Beyaz","Gri","Antrasit"]'
  },
  {
    id: "prod-asel",
    name: "Asel Series Plise Perde",
    slug: "asel-series-plise-perde",
    sku: "PLISE-ASEL",
    description: "Asel Serisi modern plise perde modelleri.",
    price: 55000,
    salePrice: 55000,
    currency: "TRY",
    stock: 100,
    category: "Asel",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 0,
    image: "/images/products/asel/asel 1.png",
    images: ["/images/products/asel/asel 1.png", "/images/products/asel/asel 2.png"],
    colors: '["Beyaz","Gri","Krem"]'
  },
  {
    id: "prod-pars",
    name: "Pars Series Plise Perde",
    slug: "pars-series-plise-perde",
    sku: "PLISE-PARS",
    description: "Pars Serisi şık ve dayanıklı plise perde modelleri.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Pars",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 0,
    image: "/images/products/pars/pars 1.png",
    images: ["/images/products/pars/pars 1.png", "/images/products/pars/pars 2.png"],
    colors: '["Gri","Antrasit","Kahve"]'
  },
  {
    id: "prod-reina",
    name: "Reina Series Plise Perde",
    slug: "reina-series-plise-perde",
    sku: "PLISE-REINA",
    description: "Reina Serisi şık ve modern plise perde.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Reina",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 0,
    image: "/images/products/reina/reina 1.png",
    images: ["/images/products/reina/reina 1.png", "/images/products/reina/reina 2.png"],
    colors: '["Beyaz","Krem","Gri"]'
  },
  {
    id: "prod-venus",
    name: "Venus Series Plise Perde",
    slug: "venus-series-plise-perde",
    sku: "PLISE-VENUS",
    description: "Venus Serisi özel ölçü plise perde.",
    price: 60500,
    salePrice: 60500,
    currency: "TRY",
    stock: 100,
    category: "Venus",
    rootCategory: "Perdeler",
    brand: "Marel",
    googleProductCategory: "Home & Garden > Decor > Window Treatments",
    active: 1,
    featured: 0,
    image: "/images/products/venus/venus 1.png",
    images: ["/images/products/venus/venus 1.png", "/images/products/venus/venus 2.png"],
    colors: '["Beyaz","Gri","Antrasit"]'
  }
];
