import Link from "next/link";
import { SiteFooter } from "@/app/components/site-footer";
import { SiteHeader } from "@/app/components/site-header";

export const metadata = { title: "Gizlilik ve İade Koşulları", description: "Marel kişisel veri, çerez, cayma ve iade koşulları hakkında bilgilendirme." };

export default function PrivacyReturnsPage() { return <><SiteHeader /><main className="legal-page"><section className="legal-hero shop-container"><span>YASAL BİLGİLENDİRME</span><h1>Gizlilik ve<br />İade Koşulları</h1><p>Son güncelleme: 8 Ağustos 2026</p></section><div className="legal-layout shop-container"><aside><a href="#gizlilik">Gizlilik</a><a href="#veriler">İşlenen veriler</a><a href="#cerezler">Çerezler</a><a href="#iade">İade ve cayma</a><a href="#ozel-uretim">Özel üretim</a><a href="#basvuru">Başvuru</a></aside><article>
  <section id="gizlilik"><span>01</span><h2>Gizlilik yaklaşımımız</h2><p>Marel; iletişim, hesap, sipariş, yorum ve destek süreçlerinde paylaştığınız bilgileri yalnız ilgili hizmeti sunmak, güvenliği sağlamak ve yasal yükümlülükleri yerine getirmek amacıyla işler. Veriler amaçla sınırlı ve ölçülü tutulur.</p></section>
  <section id="veriler"><span>02</span><h2>Hangi veriler işlenir?</h2><p>Ad-soyad, e-posta, telefon, teslimat bilgisi, sipariş ve destek kayıtları; hesabınızla giriş yaptığınızda kullanıcı kimliği; tercih vermeniz halinde analitik ve reklam ölçüm verileri işlenebilir.</p><p>KVKK kapsamındaki aydınlatma; veri sorumlusunun kimliği, işleme amacı, aktarım, toplama yöntemi ve hukuki sebep ile ilgili kişi haklarını kapsar. Detaylı başvurularınızı <Link href="/iletisim">iletişim formundan</Link> iletebilirsiniz.</p></section>
  <section id="cerezler"><span>03</span><h2>Çerezler ve ölçüm</h2><p>Sepet ve tercih bilgileri gibi zorunlu olmayan cihaz içi veriler deneyimi sürdürmek için kullanılabilir. Google ölçüm ve reklam etiketleri yalnız izin tercihiniz doğrultusunda çalışır; tercihinizi tarayıcı verilerini temizleyerek yeniden verebilirsiniz.</p></section>
  <section id="iade"><span>04</span><h2>İade ve cayma koşulları</h2><p>Mesafeli satışlarda tüketici, mevzuattaki istisnalar saklı kalmak üzere malın tesliminden itibaren 14 gün içinde cayma hakkını kullanabilir. Cayma bildiriminin yazılı veya kalıcı veri saklayıcısı ile iletilmesi gerekir. Talebiniz için sipariş numaranızla <Link href="/iletisim">bize ulaşın</Link>.</p><p>Yanlış, eksik veya ayıplı ürün bildirimleri ayrıca değerlendirilir; tüketicinin ayıplı mala ilişkin kanuni seçimlik hakları saklıdır.</p></section>
  <section id="ozel-uretim"><span>05</span><h2>Ölçüye özel ürünler</h2><p>Tüketicinin isteği veya kişisel ihtiyaçları doğrultusunda hazırlanan ürünler cayma hakkı istisnası kapsamında olabilir. Marel perde, sineklik ve kapı sistemleri onaylanan ölçü, kumaş ve profil tercihine göre üretildiğinde bu istisna uygulanabilir. Üretime başlamadan önce ölçü ve seçim teyidi alınır.</p></section>
  <section id="basvuru"><span>06</span><h2>Talep ve başvurular</h2><p>Gizlilik, veri sahipliği, sipariş, cayma veya iade taleplerinizde sipariş numarası ve iletişim bilgilerinizi belirterek <Link href="/iletisim">iletişim sayfasını</Link> veya WhatsApp hattımızı kullanabilirsiniz.</p><div className="legal-sources"><b>Resmî kaynaklar</b><a href="https://www.kvkk.gov.tr/Icerik/2033/Aydinlatma-Yukumlulugu-" target="_blank" rel="noreferrer">KVKK — Aydınlatma Yükümlülüğü ↗</a><a href="https://tuketici.ticaret.gov.tr/yayinlar/tuketici-bilgi-rehberi/mesafeli-sozlesmeler-hakkinda-bilgilendirme" target="_blank" rel="noreferrer">Ticaret Bakanlığı — Mesafeli Sözleşmeler ↗</a></div></section>
</article></div></main><SiteFooter /></>; }
